version: '3.8'

services:
  fastapi:
    build:
      dockerfile: ./Dockerfile
      context: .
    container_name: fastapi
    ports:
      - "8000:80"
    volumes:
      - ./app:/app
    environment:
      - MONGO_URL=mongodb://mongodb:27017
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${DATABASE_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${DATABASE_PASSWORD}
      - MONGO_INITDB_DATABASE=${DATABASE_NAME}
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
      - ./mongodb:/docker-entrypoint-initdb.d

volumes:
  mongo_data: