version: '3.8'

services:
  fastapi:
    build:
      dockerfile: ./Dockerfile
      context: .
    container_name: fastapi
    ports:
      - "8000:80"
    volumes:
      - ./app:/app
    environment:
      - MONGO_URL=mongodb://mongodb:27017
    depends_on:
      - mongodb

  mongodb:
    image: mongo:6
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: